### ISSUE TITLE
Sort imports by source type

### ISSUE THREAD

**Issue by SimonVanneste** [Azumuta/eslint-plugin-azumuta#3]
Sort order:
1. react
2. meteor
3. other libs
4. /imports/api
5. /imports/ui

**Comment by SimonVanneste** [comment]
@Batistleman @maximtmartin Klopt deze volgorde ongeveer?

**Comment by maximtmartin** [comment]
ja @SimonVanneste

**Comment by SimonVanneste** [comment]
Implemented in d0401daa50351bed5021afa63aa1faf9070729b9
